title: "Release mm-dd-yyyy"
labels: ["Project Releases"]
body:
  - type: markdown
    attributes:
      value: |
        **Welcome to the Release Discussion!**
  - type: dropdown
    attributes:
      label: What is the type of release?
      description: Select the release type
      options:
        - Major Release
        - Minor Release
        - Hotfix 
    validations:
      required: true
  - type: textarea
    id: deployment_info
    attributes:
      label: Deployment Information
      description: "Provide the deployment details"
      value: |
        [Post/Pre Deployment Steps](/docs/runbooks/release_mm_dd_yyyy)
      
        [Release Deployment](https://example.com)
    validations:
      required: true
  
