name: Access Request
description: Request access to an environment or system
title: 'Access Request for {Full Name of the User} - {Department}'
labels: ['access-request']
body:
  - type: dropdown
    id: submitter_check
    attributes:
      label: Are you submitting this access request for yourself?
      description: Indicate whether this access request is being submitted for yourself or on behalf of another user.
      options:
        - Myself
        - On behalf of another user
    validations:
      required: true

  - type: input
    id: access_type
    attributes:
      label: Access Type
      description: Specify the type of access being requested.
      placeholder: 'Example: Access to the Production environment'
    validations:
      required: true

  - type: input
    id: access_duration
    attributes:
      label: Duration of Access
      description: Indicate the required duration of access.
      placeholder: 'Example: 2 weeks'
    validations:
      required: true

  - type: textarea
    id: access_justification
    attributes:
      label: Justification of Access
      description: Provide the justification for requesting this access.
      placeholder: 'Example: The user just joined the IT team and need access to complete assigned tasks in the environment.'
    validations:
      required: true

  - type: dropdown
    id: manager_approval
    attributes:
      label: Manager Approved?
      description: |
        ## Has the relevant manager granted approval for this access request? If “Yes,” please attach proof of approval.
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: approval_proof
    attributes:
      label: Proof of Approval
      description: Attach a copy of the approval document or provide a link to the approval.
      placeholder: 'Example: https://company.sharepoint.com/approvals/manager_approval.pdf'
