name: Other Requests
description: Use this template to submit requests that do not fall under Bug Reports, Access Requests, or Code Optimization.
title: 'Request: {Brief Description}'
labels: ['other-requests']
body:
  - type: dropdown
    id: request_type
    attributes:
      label: Request Type/Category
      description: Select the type of request. You may select multiple, if applicable.
      multiple: true
      options:
        - Feature Request
        - Data Request
        - Documentation Update
        - Security vulnerability
        - Other
    validations:
      required: true

  - type: textarea
    id: background_info
    attributes:
      label: Background/Context
      description: Provide relevant background information or context for the request.
      placeholder: 'Example: The marketing team needs the data to generate monthly reports.'
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Urgency/Priority
      description: How urgent or critical is this request?
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: textarea
    id: expected_outcome
    attributes:
      label: Expected Outcome/Deliverables
      description: Describe the expected outcome or deliverables for this request
      placeholder: 'Example: Persona records and all assigned users should be provided in a report with documentation of their permissions.'
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Provide any extra details, links or screenshots to help understand the request
      placeholder: 'Example: Link to relevant documentation or attach supporting files.'
